### ISSUE TITLE
Chapter03　speech_to_text_02.pyで正常な音声認識ができない

### ISSUE THREAD

**Issue by hiromatsui1** [sikkimtemi/voice-chat-bot#1]
Windows11のVisual Studio Codeを使って、ダウンロードしたプログラムを実行しました。第３章のspeech_to_text_02.pyを実行して、PC内蔵マイクに「こんにちは」と話しても、「Thank you. Bye.」とか「Was that」とかが出力されます。マイクはチェックしましたが、正常に機能しています。唯一　recording_chunk = sd.rec(int(5.0 * fs), と５秒分の録音データを追加すると、時々「こんにちは」と音声認識しますが、会話を数回繰り返すとエラーが出てフリーズします。スレッドのタイミングがずれるためと思われます。

**Comment by sikkimtemi** [comment]
@hiromatsui1 
以下の環境で動作確認してみましたが、ご指摘のような現象は確認できませんでした。

- OS: Windows 11 pro
- Python 3.10.11

Pythonのバージョンを3.10にして、試していただけますか。
また、プログラムを実行すると、output.wavという名前で音声ファイルが生成されているはずなので、正常に録音されているか確認してみてください。
エラーが発生した場合は、どのようなエラーメッセージが出ているか記載していただけると助かります。

**Comment by hiromatsui1** [comment]
OS: Windows 11, Python 3.10.4, Visual studio codeの環境で、speech_to_text_02.pyを実行すると、output.wavという名前で音声ファイルが生成されます。メディアプレイヤーでこのoutput.wavを再生すると、”outputを開くことができません。サポートされていないFloat形式形式でエンコードされています”とメッセージが出てファイルが開きません。

**Comment by sikkimtemi** [comment]
@hiromatsui1 
VLC media playerなら再生できるはずです。
https://www.videolan.org/index.ja.html

それから日本語に固定して音声認識させたい場合は、次のオプションを試してみてください。

```
transcript = openai.Audio.transcribe(
    model="whisper-1", file=audio_file, language="ja"
)
```

また、次のコードも参考になるかと思います。
https://github.com/sikkimtemi/voice-interactive-chatbot/tree/main/Chapter1
OpenAIのライブラリのバージョンが異なるので、本サンプルとは若干書き方が異なります。

**Comment by hiromatsui1** [comment]
speech_to_text_02.pyについて、VLC media playerでoutput.wavを再生したところ、発話の終わりの３文字程度の音声しか録音されていませんでした。また、参考にシェアしていただいたChapter1のspeech_to_text.pyを実行しましたが、同じように発話の終わる直前の言葉しか録音されていませんでした。
一方、speech_to_text_01.pyは問題が無く録音もできていて、openaiの音声認識も日本語で正しく出力されました。たぶん、recording_chunk = sd.rec(int(0.5 * fs), samplerate=fs, channels=1)の録音時間の引数の違いによるものかと思います。

**Comment by sikkimtemi** [comment]
@hiromatsui1 
ご確認いただきありがとうございます。
現象は再現できませんが、Chapter03/speech_to_text_02.pyとChapter05/speech_to_text.pyについて、「うまく録音できない場合は録音時間を調整してください」というコメントを追加しておきました。
